name: Build and Releases
on:
  push:
    tags:
      - 'v*'
jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-24.04
            output_name: sqlift-linux-x64
            native_opts: >-
              -Ob
              --gc=serial
              -march=native
              -H:+UnlockExperimentalVMOptions
              -H:+RemoveUnusedSymbols
              -H:+RemoveUnusedDebugInfo
              -H:+RemoveSaturatedTypeFlows
              -H:+ReportExceptionStackTraces
              -H:+StackTrace
              -H:-DeleteLocalSymbols
              -H:+UseStringDeduplication
              -H:+OptimizeDiscovery
              -H:-IncludeNodeSourcePositions
              -H:InlineGraalNodeCount=2 
              -H:MaximumHeapSize=1G
              -H:+UseLightweightReflection
              -H:+TuneInlinerExploration
              -H:+InlineArrayAccess
              -H:+InlineDuringParsing
              -H:+InlineBytecodeMethods
              -H:+InlineIntrinsicsDuringParsing
              -H:+GenLoopSafepoints=false
              -H:-InstallSegfaultHandler
              -R:MaximumHeapSizePercent=80
              -H:TraceClassInitialization=false
              -H:+UseConditionalMoves
              --initialize-at-build-time
              --link-at-build-time
              --no-fallback
              --initialize-at-run-time=java.util.logging,jdk.internal.ref
              -H:ReduceImageHeapSize=true
              --no-server
          - os: macos-13
            arch: x64
            output_name: sqlift-macos-x64
            native_opts: >-
              -Ob
              --gc=serial
              -march=native
              -H:+UnlockExperimentalVMOptions
              -H:+RemoveUnusedSymbols
              -H:+RemoveUnusedDebugInfo
              -H:+RemoveSaturatedTypeFlows
              -H:+ReportExceptionStackTraces
              -H:+StackTrace
              -H:-DeleteLocalSymbols
              -H:+UseStringDeduplication
              -H:+OptimizeDiscovery
              -H:-IncludeNodeSourcePositions
              -H:InlineGraalNodeCount=2
              -H:MaximumHeapSize=1G
              -H:+UseLightweightReflection
              -H:+TuneInlinerExploration
              -H:+InlineArrayAccess
              -H:+InlineDuringParsing
              -H:+InlineBytecodeMethods
              -H:+InlineIntrinsicsDuringParsing
              -H:+GenLoopSafepoints=false
              -H:-InstallSegfaultHandler
              -R:MaximumHeapSizePercent=80
              -H:TraceClassInitialization=false
              -H:+UseConditionalMoves
              --initialize-at-build-time
              --link-at-build-time
              --no-fallback
              --initialize-at-run-time=java.util.logging,jdk.internal.ref
              -H:ReduceImageHeapSize=true
              --no-server
          - os: macos-14
            arch: arm64
            output_name: sqlift-macos-arm64
            native_opts: >-
              -Ob
              --gc=serial
              -march=native
              -H:+UnlockExperimentalVMOptions
              -H:+RemoveUnusedSymbols
              -H:+RemoveUnusedDebugInfo
              -H:+RemoveSaturatedTypeFlows
              -H:+ReportExceptionStackTraces
              -H:+StackTrace
              -H:-DeleteLocalSymbols
              -H:+UseStringDeduplication
              -H:+OptimizeDiscovery
              -H:-IncludeNodeSourcePositions
              -H:InlineGraalNodeCount=2
              -H:MaximumHeapSize=1G
              -H:+UseLightweightReflection
              -H:+TuneInlinerExploration
              -H:+InlineArrayAccess
              -H:+InlineDuringParsing
              -H:+InlineBytecodeMethods
              -H:+InlineIntrinsicsDuringParsing
              -H:+GenLoopSafepoints=false
              -H:-InstallSegfaultHandler
              -R:MaximumHeapSizePercent=80
              -H:TraceClassInitialization=false
              -H:+UseConditionalMoves
              --initialize-at-build-time
              --link-at-build-time
              --no-fallback
              --initialize-at-run-time=java.util.logging,jdk.internal.ref
              -H:ReduceImageHeapSize=true
              --no-server
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up GraalVM
        uses: graalvm/setup-graalvm@v1
        with:
          version: 'latest'
          java-version: '17'
          components: 'native-image'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          native-image-job-reports: 'true'

      - name: Configure build environment
        run: |
          echo "org.gradle.caching=true" >> gradle.properties
          echo "org.gradle.parallel=true" >> gradle.properties
          echo "org.gradle.daemon=false" >> gradle.properties
          echo "org.gradle.jvmargs=-Xmx2g -XX:MaxMetaspaceSize=512m -XX:+HeapDumpOnOutOfMemoryError" >> gradle.properties

      - name: Build with Gradle
        run: |
          ./gradlew clean
          ./gradlew build --no-daemon --parallel

      - name: Build Native Image
        run: |
          ./gradlew nativeCompile --info "-PnativeImageArgs=${{ matrix.native_opts }}"

      - name: Strip Binary
        run: |
          cd app/build/native/nativeCompile/
          strip sqlift || true

      - name: Rename Binary
        run: |
          cd app/build/native/nativeCompile/
          mv sqlift ${{ matrix.output_name }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.output_name }}
          path: app/build/native/nativeCompile/${{ matrix.output_name }}
          if-no-files-found: error

  release:
    needs: build
    runs-on: ubuntu-24.04
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v3
        with:
          path: artifacts

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            artifacts/sqlift-linux-x64/sqlift-linux-x64
            artifacts/sqlift-macos-x64/sqlift-macos-x64
            artifacts/sqlift-macos-arm64/sqlift-macos-arm64
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
