name: Build and Releases

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-14, macos-latest]  # Usamos macos-14
        include:
          - os: ubuntu-latest
            output_name: sqlift-linux-x64
          - os: macos-latest
            arch: x64
            output_name: sqlift-macos-x64
          - os: macos-14
            arch: arm64
            output_name: sqlift-macos-arm64
          - os: windows-latest
            output_name: sqlift-windows-x64

    steps:
      - uses: actions/checkout@v3

      - name: Set up GraalVM
        uses: graalvm/setup-graalvm@v1
        with:
          version: 'latest'
          java-version: '17'
          components: 'native-image,llvm-toolchain'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          native-image-job-reports: 'true'
          set-java-home: 'true'

      - name: Build with Maven
        run: mvn -B package

      - name: Build Native Image (Linux)
        if: runner.os == 'Linux'
        run: |
          native-image --no-fallback \
            -H:+ReportExceptionStackTraces \
            -H:Name=${{ matrix.output_name }} \
            --initialize-at-build-time=cl.playground.cli.CommandLineApp \
            --initialize-at-build-time=picocli \
            -cp target/sqlift.jar:target/lib/* \
            cl.playground.cli.CommandLineApp

      - name: Build Native Image (macOS x64)
        if: runner.os == 'macOS' && matrix.os == 'macos-latest'
        run: |
          native-image --no-fallback \
            -H:+ReportExceptionStackTraces \
            -H:Name=${{ matrix.output_name }} \
            --initialize-at-build-time=cl.playground.cli.CommandLineApp \
            --initialize-at-build-time=picocli \
            -cp target/sqlift.jar:target/lib/* \
            cl.playground.cli.CommandLineApp

      - name: Build Native Image (macOS arm64)
        if: runner.os == 'macOS' && matrix.os == 'macos-14'
        run: |
          native-image --no-fallback \
            -H:+ReportExceptionStackTraces \
            -H:Name=${{ matrix.output_name }} \
            --initialize-at-build-time=cl.playground.cli.CommandLineApp \
            --initialize-at-build-time=picocli \
            -cp target/sqlift.jar:target/lib/* \
            cl.playground.cli.CommandLineApp

      - name: Build Native Image (Windows)
        if: runner.os == 'Windows'
        shell: powershell
        run: |
          native-image `
            --no-fallback `
            -H:+ReportExceptionStackTraces `
            -H:Name=sqlift-windows-x64 `
            --initialize-at-build-time=cl.playground.cli.CommandLineApp `
            --initialize-at-build-time=picocli `
            "-cp" "target/sqlift.jar;target/lib/*" `
            cl.playground.cli.CommandLineApp

      - name: List Generated Files
        run: ls -R

      - name: Upload artifact (Windows)
        if: runner.os == 'Windows'
        uses: actions/upload-artifact@v3
        with:
          name: sqlift-windows-x64.exe
          path: sqlift-windows-x64.exe

      - name: Upload artifact (Linux/MacOS)
        if: runner.os != 'Windows'
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.output_name }}
          path: |
            ${{ matrix.output_name }}

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3

      - name: List Downloaded Artifacts
        run: ls -R

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            sqlift-linux-x64/sqlift-linux-x64
            sqlift-macos-x64/sqlift-macos-x64
            sqlift-macos-arm64/sqlift-macos-arm64
            sqlift-windows-x64.exe/sqlift-windows-x64.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
